### ISSUE TITLE
[BUG] Delta crashes when loading a DS save file

### ISSUE THREAD

**Issue by yolocat-dev** [rileytestut/Delta#258]
Can’t load a save file as Delta crashes when clicking on the save, tested with NSMB (DS).

**Comment by shanegillio** [comment]
Is this an in-game save or a save state?

**Comment by yolocat-dev** [comment]
A save state, save/load buttons in the Delta menu.

**Comment by shanegillio** [comment]
Are you on version 1.4.1 from AltStore? and what iOS version are you on?

**Comment by shanegillio** [comment]
Yes, you can first try updating to see if that fixes. If not, I think the beta may have fixed in and should get an official release soon.

**Comment by robm92** [comment]
Same issue. As of updating to iOS17 Beta 8 (previously working on iOS 16) I can no longer use the Load State function. It appears to load the first frame then crashes.

**Comment by robm92** [comment]
Synced the same files over to an iPad Pro and this works fine.
Tried reinstalling and syncing files back to iPhone 14 but the crash persists.

**Comment by yolocat-dev** [comment]
> Same issue. As of updating to iOS17 Beta 8 (previously working on iOS 16) I can no longer use the Load State function. It appears to load the first frame then crashes.

What version of Delta are you using? Couldn’t test with the latest as 1.4 was the latest .ipa released and I couldn’t get the project to compile myself...

**Comment by robm92** [comment]
1.4.1 through AltStore

**Comment by yolocat-dev** [comment]
@robm92 Could you try to compile the beta and check if the bug has been addressed?

**Comment by robm92** [comment]
Yes, can confirm that works. Built using Xcode 15 beta 5.

**Comment by presentttt** [comment]
> Synced the same files over to an iPad Pro and this works fine. Tried reinstalling and syncing files back to iPhone 14 but the crash persists.

So have you solved the problem？I have tried Delta1.4 and 1.3.2 released ipa file but didn't solve it, should I try to compile any beta source code? Which branch did you try to compile? Can I get the ipa file you compiled? Thanks！！！
